### ISSUE TITLE
readme fixes

### ISSUE THREAD

**Issue by sckott** [timelyportfolio/mapshaper_htmlwidget#1]
change `devtools::install_github("timelyportfolio/mapshaperWidget)` to  `devtools::install_github("timelyportfolio/mapshaper_htmlwidget")`

**Comment by sckott** [comment]
also, need a `library(sp)` in there for `sp::plot()`

**Comment by sckott** [comment]
otherwise, works nicely

**Comment by timelyportfolio** [comment]
thanks @sckott

**Comment by sckott** [comment]
:+1:
